name: Build and publish a Docker image to ghcr.io
on:

  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v4

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v14
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
